import Head from "next/head";
import { FaBars } from "react-icons/fa";
import { IoIosArrowUp } from "react-icons/io";
import Brands from "./components/Brands";
import Faqs from "./components/Faqs";
import Footer from "./components/Footer";
import Hero from "./components/Hero";
import Who from "./components/Who";

function FeaturesBox({ heading, paragraph, image }) {
  return (
    <div className="text-2xl bg-white w-[80%] md:w-[20%] h-80 rounded-lg py-8 px-4 text-tertiary shadow-lg">
      <img src={image} alt="icon" className="pb-4" />
      <h1 className="font-bold pb-4">{heading}</h1>
      <p className="text-base">{paragraph}</p>
    </div>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <section className="font-text px-8 py-4">
          <nav className="border-b-2 pb-4 flex items-center justify-between">
            <img src="/epp.png" alt="website-logo" />
            <div className="hidden md:block">
              <button className="border-primary border-2 text-lg rounded-md text-primary px-4 py-[2px] cursor-pointer">
                Sign In
              </button>
              <button className="ml-4 bg-primary px-3 py-1 text-lg rounded-md text-white cursor-pointer hover:bg-primary2 transition ease-in">
                Register an account
              </button>
            </div>
            <div className="block md:hidden">
              <FaBars size="32px" />
            </div>
          </nav>
          <div className="grid py-4">
            <ul className=" hidden md:flex justify-between items-center gap-12 justify-self-end text-lg">
              <li>Home</li>
              <li className="flex items-center gap-1">
                Ministry <IoIosArrowUp />
              </li>{" "}
              <li className="flex items-center gap-1">
                Departments <IoIosArrowUp />
              </li>
              <li className="flex items-center gap-1">
                Permits <IoIosArrowUp />
              </li>
              <li className="flex items-center gap-1">
                Guidance <IoIosArrowUp />
              </li>
              <li>Services</li>
              <li>Contact us</li>
            </ul>
          </div>
        </section>

        {/* HERO SECTION */}
        <Hero />
        {/*END OF  HERO SECTION */}

        <section className="bg-body2 py-12 font-text">
          {/* Features SECTION */}
          <div className="flex flex-col md:flex-row md:justify-center items-center gap-12">
            <FeaturesBox
              image="/user.png"
              heading="Do-It-Yourself"
              paragraph=" Apply for planning permit all by yourself and get your approved permit
        letter without hassle."
            />
            <FeaturesBox
              image="/arrow.png"
              heading="Optimised Process"
              paragraph=" Obtain your planning permit within 28 working days of submission of your application."
            />{" "}
            <FeaturesBox
              image="/people.png"
              heading="Awesome Support"
              paragraph=" Satisfaction is guaranteed, our staff are well trained to support you anytime."
            />{" "}
            <FeaturesBox
              image="/star.png"
              heading="Free Updates"
              paragraph=" ePP updates you every stage of your planning permit process. Guaranteed!"
            />
          </div>

          {/* End of Features SECTION */}

          <Who />
          <Brands />
          <Faqs />
        </section>
        <Footer />
      </div>
    </>
  );
}
