import Head from "next/head";

import Brands from "./components/Brands";
import Faqs from "./components/Faqs";
import Footer from "./components/Footer";
import Hero from "./components/Hero";
import Navbar from "./components/Navbar";
import Who from "./components/Who";

function FeaturesBox({ heading, paragraph, image }) {
  return (
    <div className="text-2xl bg-white w-[80%] md:w-[20%] h-80 rounded-lg py-8 px-4 text-tertiary shadow-lg">
      <img src={image} alt="icon" className="pb-4" />
      <h1 className="font-bold pb-4">{heading}</h1>
      <p className="text-base">{paragraph}</p>
    </div>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Epp landing page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Navbar />

        {/* HERO SECTION */}
        <Hero />
        {/*END OF  HERO SECTION */}

        <section className="bg-body2 py-12 font-text">
          {/* Features SECTION */}
          <div className="flex flex-col md:flex-row md:justify-center items-center gap-12">
            <FeaturesBox
              image="/user.png"
              heading="Do-It-Yourself"
              paragraph=" Apply for planning permit all by yourself and get your approved permit
        letter without hassle."
            />
            <FeaturesBox
              image="/arrow.png"
              heading="Optimised Process"
              paragraph=" Obtain your planning permit within 28 working days of submission of your application."
            />{" "}
            <FeaturesBox
              image="/people.png"
              heading="Awesome Support"
              paragraph=" Satisfaction is guaranteed, our staff are well trained to support you anytime."
            />{" "}
            <FeaturesBox
              image="/star.png"
              heading="Free Updates"
              paragraph=" ePP updates you every stage of your planning permit process. Guaranteed!"
            />
          </div>

          {/* End of Features SECTION */}

          <Who />
          <Brands />
          <Faqs />
        </section>
        <Footer />
      </div>
    </>
  );
}
